const OpenAI = require('openai');

const MODEL = process.env.LLM_MODEL || 'openai/gpt-4o';

// Lazy initialization — avoids crash on startup when key is not yet set
let _openai = null;
function getClient() {
  if (!_openai) {
    if (!process.env.OPENROUTER_API_KEY) {
      throw new Error('OPENROUTER_API_KEY is not set. Add it to your .env file.');
    }
    _openai = new OpenAI({
      apiKey: process.env.OPENROUTER_API_KEY,
      baseURL: 'https://openrouter.ai/api/v1',
      defaultHeaders: {
        'HTTP-Referer': process.env.APP_URL || 'http://localhost:3000',
        'X-Title': process.env.APP_NAME || 'QBE Explorer',
      },
    });
  }
  return _openai;
}

/**
 * Build the system prompt for the QBE task.
 */
function buildSystemPrompt(schemaString) {
  return `You are an expert SQL query generator for a Query-by-Example (QBE) system.
Your job is to analyze example data rows provided by the user and generate the most accurate PostgreSQL query that would return those rows (or similar rows matching the same pattern).

DATABASE SCHEMA:
${schemaString}

RULES:
1. Only use tables and columns that exist in the schema above.
2. Generate valid PostgreSQL syntax.
3. Prefer specific WHERE clauses over full table scans when the examples suggest filtering.
4. If examples suggest aggregation (count, sum, avg), include GROUP BY.
5. If examples suggest ordering, include ORDER BY.
6. Do NOT use UNION or UNION ALL.
7. Return ONLY a raw JSON object — no markdown, no code fences, no explanation outside the JSON.
8. Use this exact JSON structure:
{
  "sql": "the final SQL query",
  "explanation": "plain English explanation of what the query does and why",
  "confidence": 0.0,
  "tables_used": ["table1"],
  "reasoning": "step-by-step reasoning of how you derived the query from the examples"
}`;
}

/**
 * Build the user prompt with examples and candidate queries.
 */
function buildUserPrompt(examples, candidateQueries, naturalLanguageHint) {
  const parts = [];

  parts.push('EXAMPLE DATA (rows the user wants to find):');
  parts.push(JSON.stringify(examples, null, 2));

  if (naturalLanguageHint) {
    parts.push(`\nUSER DESCRIPTION: "${naturalLanguageHint}"`);
  }

  if (candidateQueries.length > 0) {
    parts.push('\nCANDIDATE QUERIES (generated by pattern analysis, use as hints):');
    candidateQueries.forEach((q, i) => {
      parts.push(`Candidate ${i + 1} (confidence: ${q.confidence.toFixed(2)}):\n${q.sql}`);
    });
  }

  parts.push('\nAnalyze the examples and generate the best SQL query. Return only valid JSON.');

  return parts.join('\n');
}

/**
 * Strip markdown code fences that some models wrap around JSON responses.
 * e.g. ```json { ... } ``` → { ... }
 */
function stripMarkdownFences(text) {
  if (!text) return text;
  // Remove ```json ... ``` or ``` ... ```
  return text.replace(/^```(?:json)?\s*/i, '').replace(/\s*```\s*$/, '').trim();
}

/**
 * Rank and refine candidate queries using the LLM.
 * Returns the best query with explanation.
 */
async function rankAndRefineQueries(examples, candidateQueries, schemaString, naturalLanguageHint = '') {
  const systemPrompt = buildSystemPrompt(schemaString);
  const userPrompt = buildUserPrompt(examples, candidateQueries, naturalLanguageHint);

  const response = await getClient().chat.completions.create({
    model: MODEL,
    messages: [
      { role: 'system', content: systemPrompt },
      { role: 'user', content: userPrompt },
    ],
    temperature: 0.2,
    max_tokens: 1500,
  });

  const raw = response.choices[0].message.content;
  const content = stripMarkdownFences(raw);

  try {
    const parsed = JSON.parse(content);
    return {
      sql: parsed.sql,
      explanation: parsed.explanation,
      confidence: parsed.confidence || 0.8,
      tablesUsed: parsed.tables_used || [],
      reasoning: parsed.reasoning || '',
      tokensUsed: response.usage?.total_tokens || 0,
    };
  } catch (err) {
    throw new Error(`LLM returned invalid JSON: ${raw}`);
  }
}

/**
 * Generate a natural language explanation for a given SQL query.
 */
async function explainQuery(sql, schemaString) {
  const response = await getClient().chat.completions.create({
    model: MODEL,
    messages: [
      {
        role: 'system',
        content: `You are a SQL expert. Given a SQL query and database schema, explain what the query does in plain English. Be concise and clear. Return JSON: { "explanation": "...", "what_it_returns": "...", "filters_applied": [...] }`,
      },
      {
        role: 'user',
        content: `Schema:\n${schemaString}\n\nSQL:\n${sql}\n\nExplain this query.`,
      },
    ],
    temperature: 0.1,
    max_tokens: 500,
  });

  const parsed = JSON.parse(stripMarkdownFences(response.choices[0].message.content));
  return parsed;
}

/**
 * Refine an existing query based on user feedback.
 */
async function refineQuery(originalSql, feedback, schemaString, examples) {
  const response = await getClient().chat.completions.create({
    model: MODEL,
    messages: [
      {
        role: 'system',
        content: `You are an expert SQL query refiner. Given an original query, user feedback, and the database schema, produce an improved query. Return JSON: { "sql": "...", "explanation": "...", "changes_made": "...", "confidence": 0.0-1.0, "tables_used": ["table1"] }`,
      },
      {
        role: 'user',
        content: `Schema:\n${schemaString}\n\nOriginal SQL:\n${originalSql}\n\nUser Feedback: "${feedback}"${examples.length > 0 ? `\n\nOriginal Examples:\n${JSON.stringify(examples, null, 2)}` : ''}\n\nRefine the query based on the feedback.`,
      },
    ],
    temperature: 0.2,
    max_tokens: 1000,
  });

  return JSON.parse(stripMarkdownFences(response.choices[0].message.content));
}

module.exports = { rankAndRefineQueries, explainQuery, refineQuery };
